[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/v1/*"
  to = "/.netlify/functions/nhl-api/v1/:splat"
  status = 200
