export interface MLBTeamConfig {
  sport: 'mlb';
  id: string;
  mlbId: number;
  name: string;
  city: string;
  abbreviation: string;
  slug: string;
  colors: {
    primary: string;
    secondary: string;
    accent: string;
  };
  darkMode?: {
    background: string;
    backgroundGradient?: string;
    cardBackground?: string;
    headerBackground?: string;
    accent: string;
    border: string;
    text: string;
  };
  logo: string;
}

const darkMode = (primary: string) => ({
  background: '#1a1a1a',
  backgroundGradient: 'from-[#1a1a1a] to-[#0f0f0f]',
  accent: primary,
  border: '#27272a',
  text: '#ffffff',
});

export const MLB_TEAMS: Record<string, MLBTeamConfig> = {
  diamondbacks: {
    sport: 'mlb',
    id: 'diamondbacks',
    mlbId: 109,
    name: 'Diamondbacks',
    city: 'Arizona',
    abbreviation: 'ARI',
    slug: 'diamondbacks',
    colors: { primary: '#A71930', secondary: '#E3D4AD', accent: '#000000' },
    darkMode: darkMode('#A71930'),
    logo: 'https://www.mlbstatic.com/team-logos/109.svg',
  },
  braves: {
    sport: 'mlb',
    id: 'braves',
    mlbId: 144,
    name: 'Braves',
    city: 'Atlanta',
    abbreviation: 'ATL',
    slug: 'braves',
    colors: { primary: '#CE1141', secondary: '#13274F', accent: '#EAAA00' },
    darkMode: darkMode('#CE1141'),
    logo: 'https://www.mlbstatic.com/team-logos/144.svg',
  },
  orioles: {
    sport: 'mlb',
    id: 'orioles',
    mlbId: 110,
    name: 'Orioles',
    city: 'Baltimore',
    abbreviation: 'BAL',
    slug: 'orioles',
    colors: { primary: '#DF4601', secondary: '#000000', accent: '#DF4601' },
    darkMode: darkMode('#DF4601'),
    logo: 'https://www.mlbstatic.com/team-logos/110.svg',
  },
  redsox: {
    sport: 'mlb',
    id: 'redsox',
    mlbId: 111,
    name: 'Red Sox',
    city: 'Boston',
    abbreviation: 'BOS',
    slug: 'redsox',
    colors: { primary: '#BD3039', secondary: '#0C2340', accent: '#BD3039' },
    darkMode: darkMode('#BD3039'),
    logo: 'https://www.mlbstatic.com/team-logos/111.svg',
  },
  cubs: {
    sport: 'mlb',
    id: 'cubs',
    mlbId: 112,
    name: 'Cubs',
    city: 'Chicago',
    abbreviation: 'CHC',
    slug: 'cubs',
    colors: { primary: '#0E3386', secondary: '#CC3433', accent: '#0E3386' },
    darkMode: darkMode('#0E3386'),
    logo: 'https://www.mlbstatic.com/team-logos/112.svg',
  },
  whitesox: {
    sport: 'mlb',
    id: 'whitesox',
    mlbId: 145,
    name: 'White Sox',
    city: 'Chicago',
    abbreviation: 'CWS',
    slug: 'whitesox',
    colors: { primary: '#27251F', secondary: '#C4CED4', accent: '#27251F' },
    darkMode: darkMode('#27251F'),
    logo: 'https://www.mlbstatic.com/team-logos/145.svg',
  },
  reds: {
    sport: 'mlb',
    id: 'reds',
    mlbId: 113,
    name: 'Reds',
    city: 'Cincinnati',
    abbreviation: 'CIN',
    slug: 'reds',
    colors: { primary: '#C6011F', secondary: '#000000', accent: '#C6011F' },
    darkMode: darkMode('#C6011F'),
    logo: 'https://www.mlbstatic.com/team-logos/113.svg',
  },
  guardians: {
    sport: 'mlb',
    id: 'guardians',
    mlbId: 114,
    name: 'Guardians',
    city: 'Cleveland',
    abbreviation: 'CLE',
    slug: 'guardians',
    colors: { primary: '#00385D', secondary: '#E31937', accent: '#00385D' },
    darkMode: darkMode('#00385D'),
    logo: 'https://www.mlbstatic.com/team-logos/114.svg',
  },
  rockies: {
    sport: 'mlb',
    id: 'rockies',
    mlbId: 115,
    name: 'Rockies',
    city: 'Colorado',
    abbreviation: 'COL',
    slug: 'rockies',
    colors: { primary: '#33006F', secondary: '#C4CED4', accent: '#33006F' },
    darkMode: darkMode('#33006F'),
    logo: 'https://www.mlbstatic.com/team-logos/115.svg',
  },
  tigers: {
    sport: 'mlb',
    id: 'tigers',
    mlbId: 116,
    name: 'Tigers',
    city: 'Detroit',
    abbreviation: 'DET',
    slug: 'tigers',
    colors: { primary: '#0C2340', secondary: '#FA4616', accent: '#0C2340' },
    darkMode: darkMode('#0C2340'),
    logo: 'https://www.mlbstatic.com/team-logos/116.svg',
  },
  astros: {
    sport: 'mlb',
    id: 'astros',
    mlbId: 117,
    name: 'Astros',
    city: 'Houston',
    abbreviation: 'HOU',
    slug: 'astros',
    colors: { primary: '#002D62', secondary: '#EB6E1F', accent: '#002D62' },
    darkMode: darkMode('#002D62'),
    logo: 'https://www.mlbstatic.com/team-logos/117.svg',
  },
  royals: {
    sport: 'mlb',
    id: 'royals',
    mlbId: 118,
    name: 'Royals',
    city: 'Kansas City',
    abbreviation: 'KC',
    slug: 'royals',
    colors: { primary: '#004687', secondary: '#BD9B60', accent: '#004687' },
    darkMode: darkMode('#004687'),
    logo: 'https://www.mlbstatic.com/team-logos/118.svg',
  },
  angels: {
    sport: 'mlb',
    id: 'angels',
    mlbId: 108,
    name: 'Angels',
    city: 'Los Angeles',
    abbreviation: 'LAA',
    slug: 'angels',
    colors: { primary: '#BA0021', secondary: '#003263', accent: '#BA0021' },
    darkMode: darkMode('#BA0021'),
    logo: 'https://www.mlbstatic.com/team-logos/108.svg',
  },
  dodgers: {
    sport: 'mlb',
    id: 'dodgers',
    mlbId: 119,
    name: 'Dodgers',
    city: 'Los Angeles',
    abbreviation: 'LAD',
    slug: 'dodgers',
    colors: { primary: '#005A9C', secondary: '#EF3E42', accent: '#005A9C' },
    darkMode: darkMode('#005A9C'),
    logo: 'https://www.mlbstatic.com/team-logos/119.svg',
  },
  marlins: {
    sport: 'mlb',
    id: 'marlins',
    mlbId: 146,
    name: 'Marlins',
    city: 'Miami',
    abbreviation: 'MIA',
    slug: 'marlins',
    colors: { primary: '#00A3E0', secondary: '#EF3340', accent: '#000000' },
    darkMode: darkMode('#00A3E0'),
    logo: 'https://www.mlbstatic.com/team-logos/146.svg',
  },
  brewers: {
    sport: 'mlb',
    id: 'brewers',
    mlbId: 158,
    name: 'Brewers',
    city: 'Milwaukee',
    abbreviation: 'MIL',
    slug: 'brewers',
    colors: { primary: '#FFC52F', secondary: '#12284B', accent: '#FFC52F' },
    darkMode: darkMode('#FFC52F'),
    logo: 'https://www.mlbstatic.com/team-logos/158.svg',
  },
  twins: {
    sport: 'mlb',
    id: 'twins',
    mlbId: 142,
    name: 'Twins',
    city: 'Minnesota',
    abbreviation: 'MIN',
    slug: 'twins',
    colors: { primary: '#002B5C', secondary: '#D31145', accent: '#002B5C' },
    darkMode: darkMode('#002B5C'),
    logo: 'https://www.mlbstatic.com/team-logos/142.svg',
  },
  mets: {
    sport: 'mlb',
    id: 'mets',
    mlbId: 121,
    name: 'Mets',
    city: 'New York',
    abbreviation: 'NYM',
    slug: 'mets',
    colors: { primary: '#002D72', secondary: '#FF5910', accent: '#002D72' },
    darkMode: darkMode('#002D72'),
    logo: 'https://www.mlbstatic.com/team-logos/121.svg',
  },
  yankees: {
    sport: 'mlb',
    id: 'yankees',
    mlbId: 147,
    name: 'Yankees',
    city: 'New York',
    abbreviation: 'NYY',
    slug: 'yankees',
    colors: { primary: '#003087', secondary: '#E4002C', accent: '#003087' },
    darkMode: darkMode('#003087'),
    logo: 'https://www.mlbstatic.com/team-logos/147.svg',
  },
  athletics: {
    sport: 'mlb',
    id: 'athletics',
    mlbId: 133,
    name: 'Athletics',
    city: 'Oakland',
    abbreviation: 'OAK',
    slug: 'athletics',
    colors: { primary: '#003831', secondary: '#EFB21E', accent: '#003831' },
    darkMode: darkMode('#003831'),
    logo: 'https://www.mlbstatic.com/team-logos/133.svg',
  },
  phillies: {
    sport: 'mlb',
    id: 'phillies',
    mlbId: 143,
    name: 'Phillies',
    city: 'Philadelphia',
    abbreviation: 'PHI',
    slug: 'phillies',
    colors: { primary: '#E81828', secondary: '#002D72', accent: '#E81828' },
    darkMode: darkMode('#E81828'),
    logo: 'https://www.mlbstatic.com/team-logos/143.svg',
  },
  pirates: {
    sport: 'mlb',
    id: 'pirates',
    mlbId: 134,
    name: 'Pirates',
    city: 'Pittsburgh',
    abbreviation: 'PIT',
    slug: 'pirates',
    colors: { primary: '#27251F', secondary: '#FDB827', accent: '#27251F' },
    darkMode: darkMode('#27251F'),
    logo: 'https://www.mlbstatic.com/team-logos/134.svg',
  },
  padres: {
    sport: 'mlb',
    id: 'padres',
    mlbId: 135,
    name: 'Padres',
    city: 'San Diego',
    abbreviation: 'SD',
    slug: 'padres',
    colors: { primary: '#2F241D', secondary: '#FFC425', accent: '#2F241D' },
    darkMode: darkMode('#2F241D'),
    logo: 'https://www.mlbstatic.com/team-logos/135.svg',
  },
  giants: {
    sport: 'mlb',
    id: 'giants',
    mlbId: 137,
    name: 'Giants',
    city: 'San Francisco',
    abbreviation: 'SF',
    slug: 'giants',
    colors: { primary: '#FD5A1E', secondary: '#27251F', accent: '#FD5A1E' },
    darkMode: darkMode('#FD5A1E'),
    logo: 'https://www.mlbstatic.com/team-logos/137.svg',
  },
  mariners: {
    sport: 'mlb',
    id: 'mariners',
    mlbId: 136,
    name: 'Mariners',
    city: 'Seattle',
    abbreviation: 'SEA',
    slug: 'mariners',
    colors: { primary: '#0C2C56', secondary: '#005C5C', accent: '#0C2C56' },
    darkMode: darkMode('#0C2C56'),
    logo: 'https://www.mlbstatic.com/team-logos/136.svg',
  },
  cardinals: {
    sport: 'mlb',
    id: 'cardinals',
    mlbId: 138,
    name: 'Cardinals',
    city: 'St. Louis',
    abbreviation: 'STL',
    slug: 'cardinals',
    colors: { primary: '#C41E3A', secondary: '#0C2340', accent: '#C41E3A' },
    darkMode: darkMode('#C41E3A'),
    logo: 'https://www.mlbstatic.com/team-logos/138.svg',
  },
  rays: {
    sport: 'mlb',
    id: 'rays',
    mlbId: 139,
    name: 'Rays',
    city: 'Tampa Bay',
    abbreviation: 'TB',
    slug: 'rays',
    colors: { primary: '#092C5C', secondary: '#8FBCE6', accent: '#092C5C' },
    darkMode: darkMode('#092C5C'),
    logo: 'https://www.mlbstatic.com/team-logos/139.svg',
  },
  txrangers: {
    sport: 'mlb',
    id: 'txrangers',
    mlbId: 140,
    name: 'Rangers',
    city: 'Texas',
    abbreviation: 'TEX',
    slug: 'txrangers',
    colors: { primary: '#003278', secondary: '#C0111F', accent: '#003278' },
    darkMode: darkMode('#003278'),
    logo: 'https://www.mlbstatic.com/team-logos/140.svg',
  },
  bluejays: {
    sport: 'mlb',
    id: 'bluejays',
    mlbId: 141,
    name: 'Blue Jays',
    city: 'Toronto',
    abbreviation: 'TOR',
    slug: 'bluejays',
    colors: { primary: '#134A8E', secondary: '#E8291C', accent: '#134A8E' },
    darkMode: darkMode('#134A8E'),
    logo: 'https://www.mlbstatic.com/team-logos/141.svg',
  },
  nationals: {
    sport: 'mlb',
    id: 'nationals',
    mlbId: 120,
    name: 'Nationals',
    city: 'Washington',
    abbreviation: 'WSH',
    slug: 'nationals',
    colors: { primary: '#AB0003', secondary: '#14225A', accent: '#AB0003' },
    darkMode: darkMode('#AB0003'),
    logo: 'https://www.mlbstatic.com/team-logos/120.svg',
  },
};
