/**
 * Generate lib/data/nhlPriorPace.ts: each team's preseason talent estimate for
 * the coming NHL season (last season's points pace regressed toward the league
 * average). The live odds model regresses early-season pace toward these
 * instead of the flat league average, so odds don't snap to ~50% on game 1.
 *
 * Run once per offseason, after the prior regular season ends:
 *   npx tsx scripts/build-nhl-prior-pace.ts [--season 20262027]
 */

import { writeFileSync } from 'fs';
import { join } from 'path';
import { priorPaceFromLastSeason } from '../lib/utils/nhlPriorPace';
import { getCurrentNHLSeason, previousNHLSeason } from '../lib/utils/season';

const NHL_API = 'https://api-web.nhle.com/v1';

function arg(name: string, fallback: string): string {
  const i = process.argv.indexOf(`--${name}`);
  return i >= 0 && process.argv[i + 1] ? process.argv[i + 1] : fallback;
}

async function main() {
  const season = arg('season', getCurrentNHLSeason());
  const last = previousNHLSeason(season);

  const seasons = await (await fetch(`${NHL_API}/standings-season`)).json();
  const end = seasons.seasons.find((s: { id: number }) => String(s.id) === last)?.standingsEnd;
  if (!end) throw new Error(`No standings end date for ${last}`);

  const { standings } = await (await fetch(`${NHL_API}/standings/${end}`)).json();
  if (!Array.isArray(standings) || standings.length < 30) throw new Error(`No final standings for ${last}`);

  const rows = standings
    .map((t: { teamAbbrev: { default: string }; points: number; gamesPlayed: number }) =>
      [t.teamAbbrev.default, priorPaceFromLastSeason(t.points, t.gamesPlayed)] as const)
    .sort((a: readonly [string, number], b: readonly [string, number]) => a[0].localeCompare(b[0]));

  const body = rows.map(([abbrev, pace]: readonly [string, number]) => `    ${abbrev}: ${pace.toFixed(4)},`).join('\n');
  const file = `// Generated by scripts/build-nhl-prior-pace.ts from ${last} final standings (${end}).
// Preseason talent estimate in points per game; regenerate each offseason.
export const NHL_PRIOR_PACE: Record<string, Record<string, number>> = {
  '${season}': {
${body}
  },
};
`;
  writeFileSync(join(process.cwd(), 'lib', 'data', 'nhlPriorPace.ts'), file);
  console.log(`Wrote ${rows.length} teams for ${season} from ${last} standings (${end})`);
}

main().catch(err => {
  console.error(err);
  process.exit(1);
});
